# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{grizzly}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Grzegorz Kazulak"]
  s.date = %q{2010-06-29}
  s.description = %q{Control access like a Bear}
  s.email = %q{grzegorz.kazulak@gmail.com}
  s.files = [
    ".gitignore",
     "Gemfile",
     "Rakefile",
     "VERSION",
     "grizzly.gemspec",
     "lib/grizzly.rb",
     "lib/grizzly/configuration.rb",
     "lib/grizzly/logger.rb",
     "spec/configuration_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/grzegorzkazulak/grizzly/grizzly}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{grizzly}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{ACL for Rails 3}
  s.test_files = [
    "spec/configuration_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<railties>, [">= 3.0.0.beta4"])
    else
      s.add_dependency(%q<railties>, [">= 3.0.0.beta4"])
    end
  else
    s.add_dependency(%q<railties>, [">= 3.0.0.beta4"])
  end
end

